# Generated by Django 2.0.7 on 2018-10-29 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterSWRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('passcode', models.CharField(blank=True, max_length=100, null=True)),
                ('default_avatar', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SWRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('passcode', models.CharField(blank=True, max_length=100)),
                ('created_on', models.DateTimeField()),
                ('open_to_all', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SWRoomChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_text', models.CharField(blank=True, max_length=200, null=True)),
                ('avatar', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('room_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='swdice.SWRoom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SWRoomDestiny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_pips', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('dark_pips', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('room_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='swdice.SWRoom')),
            ],
        ),
        migrations.CreateModel(
            name='SWRoomToUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admitted', models.BooleanField(default=True)),
                ('game_master', models.BooleanField(default=False)),
                ('banned', models.BooleanField(default=False)),
                ('date_link_created', models.DateTimeField(auto_now_add=True)),
                ('date_admitted', models.DateTimeField(blank=True, null=True)),
                ('date_made_gm', models.DateTimeField(blank=True, null=True)),
                ('date_banned', models.DateTimeField(blank=True, null=True)),
                ('default_avatar_is_user', models.BooleanField(default=True)),
                ('avatar_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Avatar')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swdice.SWRoom')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
