# Generated by Django 2.0.7 on 2018-10-30 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swdice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swroomchat',
            name='avatar',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Avatar'),
        ),
    ]
