# Generated by Django 2.0.7 on 2018-10-30 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swdice', '0002_auto_20181030_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swroomchat',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swdice.SWRoom'),
        ),
    ]
