# Generated by Django 2.0.7 on 2018-11-06 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('swdice', '0003_auto_20181030_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='SWDicePool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_boost_dice', models.PositiveSmallIntegerField(default=0)),
                ('num_setback_dice', models.PositiveSmallIntegerField(default=0)),
                ('num_ability_dice', models.PositiveSmallIntegerField(default=0)),
                ('num_difficulty_dice', models.PositiveSmallIntegerField(default=0)),
                ('num_proficiency_dice', models.PositiveSmallIntegerField(default=0)),
                ('num_challenge_dice', models.PositiveSmallIntegerField(default=0)),
                ('num_force_dice', models.PositiveSmallIntegerField(default=0)),
                ('faces_boost', models.CharField(blank=True, max_length=50, null=True)),
                ('faces_setback', models.CharField(blank=True, max_length=50, null=True)),
                ('faces_ability', models.CharField(blank=True, max_length=50, null=True)),
                ('faces_difficulty', models.CharField(blank=True, max_length=50, null=True)),
                ('faces_proficiency', models.CharField(blank=True, max_length=50, null=True)),
                ('faces_challenge', models.CharField(blank=True, max_length=50, null=True)),
                ('faces_force', models.CharField(blank=True, max_length=50, null=True)),
                ('results_triumph', models.PositiveSmallIntegerField(default=0)),
                ('results_despair', models.PositiveSmallIntegerField(default=0)),
                ('results_success', models.PositiveSmallIntegerField(default=0)),
                ('results_failure', models.PositiveSmallIntegerField(default=0)),
                ('results_advantage', models.PositiveSmallIntegerField(default=0)),
                ('results_disadvantage', models.PositiveSmallIntegerField(default=0)),
                ('results_light_pips', models.PositiveSmallIntegerField(default=0)),
                ('results_dark_pips', models.PositiveSmallIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Avatar')),
                ('swroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='swdice.SWRoom')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
