# Generated by Django 2.0.7 on 2018-11-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swdice', '0005_swdicepool_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='swdicepool',
            name='additional_advantage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='swdicepool',
            name='additional_dark_pips',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='swdicepool',
            name='additional_despair',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='swdicepool',
            name='additional_disadvantage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='swdicepool',
            name='additional_failure',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='swdicepool',
            name='additional_light_pips',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='swdicepool',
            name='additional_success',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='swdicepool',
            name='additional_triumph',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
