# Generated by Django 2.0.7 on 2018-11-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swdice', '0006_auto_20181106_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='swdicepool',
            name='num_numerical_dice',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='swdicepool',
            name='numerical_dice_sides',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
