# Generated by Django 2.0.7 on 2018-11-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swdice', '0009_swdicepool_results_numerical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swdicepool',
            name='faces_ability',
        ),
        migrations.RemoveField(
            model_name='swdicepool',
            name='faces_boost',
        ),
        migrations.RemoveField(
            model_name='swdicepool',
            name='faces_challenge',
        ),
        migrations.RemoveField(
            model_name='swdicepool',
            name='faces_difficulty',
        ),
        migrations.RemoveField(
            model_name='swdicepool',
            name='faces_force',
        ),
        migrations.RemoveField(
            model_name='swdicepool',
            name='faces_proficiency',
        ),
        migrations.RemoveField(
            model_name='swdicepool',
            name='faces_setback',
        ),
        migrations.AddField(
            model_name='swdicepool',
            name='faces_summary',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
