# Generated by Django 2.0.7 on 2018-11-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swdice', '0010_auto_20181107_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swdicepool',
            old_name='additional_disadvantage',
            new_name='additional_threat',
        ),
        migrations.RenameField(
            model_name='swdicepool',
            old_name='results_disadvantage',
            new_name='results_threat',
        ),
    ]
